### ISSUE TITLE
Simple assignement with Number+"+" or Number+"-" does not work

### ISSUE THREAD

**Issue by croraf** [jasonwilliams/boa#224]
Simple assignement with addition does not work when there is no space between first operand and  "+" or "-":
```
let a = 1+ 2;
```

This works though:
```
let a = 1 + 2;
```

Same with "-" binary operator.

```
thread 'main' panicked at 'Could not convert value to f64: ParseFloatError { kind: Invalid }', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:960
  16: boa::syntax::lexer::Lexer::lex
             at src/lib/syntax/lexer.rs:401
  17: boa::parser_expr
             at src/lib/lib.rs:52
  18: boa::forward
             at src/lib/lib.rs:61
  19: boa::exec
             at src/lib/lib.rs:84
  20: boa::main
             at src/bin/bin.rs:57```

**Comment by gomesalexandre** [comment]
This is coming from here https://github.com/jasonwilliams/boa/blob/master/src/lib/syntax/lexer.rs#L430
It seems like once you add a space, the `+` is pushed to `buf`, so we make a call to the `f64::from_str` with `1+`.

I'll have a look, I wanted to get started contributing to boa since the talk at JSConf EU so that would be an amazing first task for it!
